### ISSUE TITLE
Won't work - gives an error when trying to load a pdf

### ISSUE THREAD

**Issue by bioboy** [adasilva/journal2ebook#33]
I'm trying to get journal2ebook working on Ubuntu 18.04 and it exits with the error below when trying to load a PDF.

> convert-im6.q16: not authorized `/home/troy/Documents/some-file.pdf' @ error/constitute.c/ReadImage/412.
convert-im6.q16: no images defined `/home/troy/Documents/tempfiles/temp.png' @ error/convert.c/ConvertImageCommand/3258.
Couldn't load file:  [Errno 2] No such file or directory: '/home/troy/Documents/tempfiles/temp.png'
Traceback (most recent call last):
  File "/usr/local/bin/journal2ebook", line 481, in <module>
    myapp=Journal2ebook(root,filename)
  File "/usr/local/bin/journal2ebook", line 94, in __init__
    self.setup()
  File "/usr/local/bin/journal2ebook", line 102, in setup
    self.prepImage()
  File "/usr/local/bin/journal2ebook", line 268, in prepImage
    self.imgaspect = float(self.img.size[0]) / float(self.img.size[1])
AttributeError: 'NoneType' object has no attribute 'size'

**Comment by jrpenaneto** [comment]
Same problem here. Lubuntu 18.4, python 2.7.15.

**Comment by johnblommers** [comment]
Same problem here with Ubuntu 19.10. Right after selecting a PDF for conversion `journal2ebook` crashes with:

> convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408.
> convert-im6.q16: no images defined `/home/johnb/Documents/tempfiles/temp.png' @ error/convert.c/ConvertImageCommand/3258.
> Couldn't load file:  [Errno 2] No such file or directory: '/home/johnb/Documents/tempfiles/temp.png'
Traceback (most recent call last):
>  File "journal2ebook.py", line 493, in <module>
    myapp=Journal2ebook(root,filename)
>  File "journal2ebook.py", line 97, in __init__
    self.setup()
>  File "journal2ebook.py", line 105, in setup
    self.prepImage()
>  File "journal2ebook.py", line 279, in prepImage
    self.imgaspect = float(self.img.size[0]) / float(self.img.size[1])
> AttributeError: 'NoneType' object has no attribute 'size'
